#pragma once
#include <iostream>
#include <fstream>
#include <stdio.h>
#include <cstdlib>
#include <allegro5\allegro.h>
#include <allegro5\allegro_native_dialog.h>
#include <string>
#include "menu.h"
#include "przycisk_txt.h"
#include "przycisk_img.h"
#include "silnik.h"
#include "gra.h"